/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Thu Apr 23 09:46:38 2020 */

/* parameterized module instance */
pll_sensor_clk __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
